export const ShopActionTypes = {
  SHOPS_FETCH_START: 'SHOPS_FETCH_START',
  SHOPS_FETCH_SUCCESS: 'SHOPS_FETCH_SUCCESS',
  SHOPS_FETCH_ERROR: 'SHOPS_FETCH_ERROR',

  SHOP_FETCH_START: 'SHOP_FETCH_START',
  SHOP_FETCH_SUCCESS: 'SHOP_FETCH_SUCCESS',
  SHOP_FETCH_ERROR: 'SHOP_FETCH_ERROR',

  SHOP_CREATE_START: 'SHOP_CREATE_START',
  SHOP_CREATE_SUCCESS: 'SHOP_CREATE_SUCCESS',
  SHOP_CREATE_ERROR: 'SHOP_CREATE_ERROR',
  CLEAR_SHOP_CREATE_SUCCESS: 'CLEAR_SHOP_CREATE_SUCCESS',

  SHOP_UPDATE_START: 'SHOP_UPDATE_START',
  SHOP_UPDATE_SUCCESS: 'SHOP_UPDATE_SUCCESS',
  SHOP_UPDATE_ERROR: 'SHOP_UPDATE_ERROR',

  CART_POST_START: 'CART_FETCH_START',
  CART_POST_SUCCESS: 'CART_FETCH_SUCCESS',
  CART_POST_ERROR: 'CART_FETCH_ERROR',
};
